ALTER TABLE `TREDE_PERMISSAO` ADD COLUMN `DESC` TEXT NULL COMMENT 'decrição do menu AFTER `SITUACAO` ';

ALTER TABLE `TREDE_PERMISSAO` CHANGE `DESC` `DESCR` TEXT CHARSET utf8 COLLATE utf8_unicode_ci NULL COMMENT 'decrição do menu';

CREATE TABLE `TREDE_DOTBANK_CONFIG_REDE` ( `SEQ` INT(11) AUTO_INCREMENT, `SEQUENCIACRE` INT(11), `CNPJ` VARCHAR(30), `SENHA` VARCHAR(100), KEY(`SEQ`) );

ALTER TABLE `TREDE_PAGACOMPRA` ADD COLUMN `CTIPINTECOMPRA` VARCHAR(2) NULL COMMENT 'SE FOI INTEGRAL OU PARCIAL COM ESTRELAS]' AFTER `CTIPPPAGCOMPRA`;

ALTER TABLE `TREDE_ADMINS` ADD COLUMN `CNOMEADMIN` VARCHAR(400) NULL COMMENT 'NOME DO USUARIO' AFTER `NNUMEADMIN`;

CREATE TABLE `TREDE_PERMISSAO_ADMIN` ( `NNUMEADMIN` INT(11) AUTO_INCREMENT, `NNIVEADMIN` INT(11) COMMENT 'NIVEL', `CNIVEADMIN` VARCHAR(10) COMMENT 'O QUE PODE FAZER', KEY(`NNUMEADMIN`) );

INSERT INTO `TREDE_PERMISSAO_ADMIN` (`NNIVEADMIN`) VALUES ('1');
INSERT INTO `TREDE_PERMISSAO_ADMIN` (`NNIVEADMIN`) VALUES ('2');
INSERT INTO `TREDE_PERMISSAO_ADMIN` (`NNIVEADMIN`) VALUES ('3');
INSERT INTO `TREDE_PERMISSAO_ADMIN` (`NNIVEADMIN`) VALUES ('4');

UPDATE `TREDE_PERMISSAO_ADMIN` SET `CNIVEADMIN` = 'C' WHERE `NNUMEADMIN` = '1' AND `NNIVEADMIN` = '1' AND `CNIVEADMIN` IS NULL;
UPDATE `TREDE_PERMISSAO_ADMIN` SET `CNIVEADMIN` = 'CB' WHERE `NNUMEADMIN` = '2' AND `NNIVEADMIN` = '2' AND `CNIVEADMIN` IS NULL;
UPDATE `TREDE_PERMISSAO_ADMIN` SET `CNIVEADMIN` = 'CCAB' WHERE `NNUMEADMIN` = '3' AND `NNIVEADMIN` = '3' AND `CNIVEADMIN` IS NULL;
UPDATE `TREDE_PERMISSAO_ADMIN` SET `CNIVEADMIN` = 'CCABA' WHERE `NNUMEADMIN` = '4' AND `NNIVEADMIN` = '4' AND `CNIVEADMIN` IS NULL;


ALTER TABLE `TREDE_ADMINS` ADD COLUMN `REDE_SEQUSUA` INT(11) NULL COMMENT 'SEQUENCIA DO USUARIO' AFTER `SENHAADMIN`;

ALTER TABLE `TREDE_ADMINS` ADD COLUMN `CSITUADMIN` VARCHAR(1) NULL COMMENT 'SITUAÇÃO DO USUARIO' AFTER `REDE_SEQUSUA`;


CREATE TABLE `TREDE_DOTBANK_USUA` ( `NNUMEDOT` INT AUTO_INCREMENT, `REDE_SEQUSUA` INT(11), `NCPF_DOT` VARCHAR(20), `NRG__DOT` INT(11), `SENHADOT` VARCHAR(300), `ENDERDOT` VARCHAR(500), `NENDEDOT` VARCHAR(10), `CIDADDOT` VARCHAR(500), `ESTADDOT` VARCHAR(20), `CCEP_DOT` VARCHAR(20), `COMPLDOT` VARCHAR(300), `BAIRRDOT` VARCHAR(500), KEY(`NNUMEDOT`) );

ALTER TABLE `TREDE_DOTBANK_USUA` ADD COLUMN `CSITUDOT` VARCHAR(1) NULL AFTER `BAIRRDOT`;


CREATE TABLE `TREDE_PACOTES_REDE` ( `NNUMEPAC` INT AUTO_INCREMENT, `CNOMEPAC` VARCHAR(300) COMMENT 'NOME DO PACOTE', `CDESCPAC` TEXT COMMENT 'DESCRIÇÃO DO PACOTE', `NPONTPAC` VARCHAR(100) COMMENT 'UQANTIDADE DOS PACOTES', `CSITUPAC` VARCHAR(2) COMMENT 'SITUAÇÃO DO PACOTE', KEY(`NNUMEPAC`) );

ALTER TABLE `TREDE_PACOTES_REDE` ADD COLUMN `NVALOPAC` VARCHAR(30) NULL COMMENT 'VALOR DO PACOTE' AFTER `CSITUPAC`;

CREATE TABLE `TREDE_PAGAPACOTE` ( `NNUMEPPAC` INT(11) AUTO_INCREMENT, `NNUMEREDE` INT(11) COMMENT 'SEQUENCIA DA REDE', `NNUMEPAC` INT(11) COMMENT 'SEQNCIA DO PACOTE', `SITPAGPAC` VARCHAR(10) COMMENT 'SITUAÇÃO DO PAGAMENTO DO PACOTE', `NVALOPPAC` VARCHAR(30) COMMENT 'VALOR DO PACOTE', `NPONTPPAC` VARCHAR(30) COMMENT 'PONTUAÇÃO DO PACOTE', `TIPOPPPAC` VARCHAR(100) COMMENT 'TIPO DE PAGMENTO', KEY(`NNUMEPPAC`) );

ALTER TABLE `TREDE_PAGAPACOTE` ADD COLUMN `DDATAPPAC` DATETIME NULL COMMENT 'DATA E HORA DA TRANSIÇÃO' AFTER `TIPOPPPAC`;

ALTER TABLE `TREDE_PAGAPACOTE` ADD COLUMN `CIDPGPPAC` VARCHAR(30) NULL COMMENT 'ID QUE VAI PARA API' AFTER `DDATAPPAC`;

ALTER TABLE `TREDE_PAGAPACOTE` ADD COLUMN `CIDDPGPAC` VARCHAR(100) NULL COMMENT 'ID DO BOLETO' AFTER `CIDPGPPAC`;

ALTER TABLE `TREDE_DOTBANK_USUA` ADD COLUMN `DNASCDOT` DATE NULL AFTER `CSITUDOT`;

ALTER TABLE `TREDE_CREDITOTRANS_REDE` ADD COLUMN `CTIPONTOREDE` VARCHAR(50) NULL COMMENT 'TIPO DA COBRANÇA DOT OU PAGSEGURO' AFTER `TIPCREDTREDE`;

CREATE TABLE `TREDE_CONTRATOS` ( `SEQ` INT(11) AUTO_INCREMENT, `NOME` VARCHAR(500), `DATA` DATETIME, KEY(`SEQ`) );

CREATE TABLE `TREDE_SINDICATOS` ( `NNUMESIND` INT(11) AUTO_INCREMENT COMMENT 'ID', `CNOMESIND` VARCHAR(300) COMMENT 'CNOME', `CNPJ_SIND` VARCHAR(30) COMMENT 'CNPJ', `CENDESIND` VARCHAR(400) COMMENT 'ENBDEREÇO', `NENDESIND` VARCHAR(50) COMMENT 'NUMEROI DO ENDEREÇO', `CCEP_SIND` VARCHAR(12) COMMENT 'CEP', `CBAIRSIND` VARCHAR(300) COMMENT 'BAIRRO', `CCIDASIND` VARCHAR(300) COMMENT 'CIDADE', `CESTASIND` VARCHAR(2) COMMENT 'ESTADO', `CEMAISIND` VARCHAR(400) COMMENT 'EMAIL', `CSENHSIND` VARCHAR(200) COMMENT 'SENHA', `CIMAGSIND` VARCHAR(500) COMMENT 'IMAGEM', KEY(`NNUMESIND`) );

ALTER TABLE `TREDE_SINDICATOS` ADD COLUMN `CTELESIND` VARCHAR(20) NULL AFTER `CIMAGSIND`, ADD COLUMN `CCELUSIND` VARCHAR(20) NULL AFTER `CTELESIND`;

ALTER TABLE `TREDE_SINDICATOS` ADD COLUMN `CSITUSIND` CHAR(1) NULL COMMENT 'SITUAÇÃO' AFTER `CCELUSIND`;

ALTER TABLE `TREDE_SINDICATOS` ADD COLUMN `DINCLSIND` DATE NULL COMMENT 'DATA DA INCLUSÃO' AFTER `CSITUSIND`;

ALTER TABLE `TREDE_SINDICATOS` ADD COLUMN `CCOMPSIND` VARCHAR(1000) NULL COMMENT 'COMPLEMENTO' AFTER `DINCLSIND`;

ALTER TABLE `TREDE_PAGAPACOTE` ADD COLUMN `CSITUAPAC` CHAR(1) NULL COMMENT 'SITUAÇÃO DO PACOTE' AFTER `CIDDPGPAC`;

ALTER TABLE `TREDE_PAGAPACOTE` ADD COLUMN `DPAGPCPAC` DATETIME NULL COMMENT 'DATA DA EFETIVAÇÃO' AFTER `CSITUAPAC`;

CREATE TABLE `TREDE_PAGSEGURO_REDE` ( `SEQ` INT(11) AUTO_INCREMENT, `SEQUENCIACRE` INT(11) COMMENT 'NUMERO DA REDE', `EMAIL` VARCHAR(500) COMMENT 'EMAIL DO PAG SEGURO', `TOKEN` VARCHAR(500) COMMENT 'TOKEN DO PAG SEGURO', KEY(`SEQ`) );

ALTER TABLE `TREDE_PAGAPACOTE` ADD COLUMN `CTPBAIPAC` VARCHAR(100) NULL COMMENT 'TIPO DA BAIXA' AFTER `DPAGPCPAC`;

CREATE TABLE `TREDE_SINDICATO_USUA` ( `NNUMESIUS` INT(11) COMMENT 'SEQ', `NNUMESIND` INT(11) COMMENT 'NUMERO DO SINDICATO', `NNUMEUSUA` INT(11) COMMENT 'NUMERO DO USUARIO', `CSITUSIUS` CHAR(1) COMMENT 'SITUAÇÃO', `DINCLSIUS` DATETIME COMMENT 'DATA DA INCLUSAO' );

ALTER TABLE `TREDE_SINDICATO_USUA` CHANGE `NNUMESIUS` `NNUMESIUS` INT(11) NULL AUTO_INCREMENT COMMENT 'SEQ', ADD KEY(`NNUMESIUS`);

ALTER TABLE `TREDE_SINDICATOS` ADD COLUMN `BLOCKSIND` CHAR(1) NULL AFTER `CCOMPSIND`;

ALTER TABLE `TREDE_SINDICATO_USUA` ADD COLUMN `CSTATSIUS` CHAR(1) NULL AFTER `DINCLSIUS`;

ALTER TABLE `TREDE_SINDICATO_USUA` CHANGE `CSTATSIUS` `CSTATSIUS` CHAR(1) CHARSET utf8 COLLATE utf8_unicode_ci NULL COMMENT 'STATUS DOSS PEDIDO DE CANCELAMENTO', ADD COLUMN `DCANCSIUS` DATETIME NULL COMMENT 'DATA DO CANCELAMENTO' AFTER `CSTATSIUS`;

CREATE TABLE `TREDE_SINDICATO_USUA_CANCELADOS` ( KEY `NNUMESIUS`( `NNUMESIUS` ))ENGINE=MYISAM COLLATE = utf8_unicode_ci COMMENT = '' SELECT `NNUMESIUS`, `NNUMESIND`, `NNUMEUSUA`, `CSITUSIUS`, `DINCLSIUS`, `CSTATSIUS`, `DCANCSIUS` FROM `TREDE_SINDICATO_USUA` WHERE 1 = 0;

ALTER TABLE `TREDE_SINDICATO_USUA_CANCELADOS` DROP COLUMN `DINCLSIUS`, DROP COLUMN `CSTATSIUS`;

ALTER TABLE `TREDE_SINDICATO_USUA_CANCELADOS` CHANGE `CSTATSIUS` `CSTATSIUS` VARCHAR(10) CHARSET utf8 COLLATE utf8_unicode_ci NULL COMMENT 'SITUAÇÃO';

CREATE TABLE `TREDE_EMAIL` ( `TITULO` VARCHAR(4000) COMMENT 'TITULO DO EMAIL', `TEXTO` TEXT COMMENT 'TEXTO DO EMAIL' );

ALTER TABLE `TREDE_ADMINS` ADD COLUMN `MASTER` CHAR(1) NULL COMMENT 'SÓ ADMIN MASTER' AFTER `CSITUADMIN`;

ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `LINKBOLETO` VARCHAR(1000) NULL COMMENT 'LINK DDO BOLETO' AFTER `CTIPOOPPLAN`;

ALTER TABLE `TREDE_PAGAPLANO` CHANGE `CSITPAGPLAN` `CSITPAGPLAN` VARCHAR(5) CHARSET utf8 COLLATE utf8_general_ci NULL COMMENT 'SITUAÇÃO DO PAGAMENTO DO PLANO';

ALTER TABLE `TREDE_USUADMIN` ADD COLUMN `REDE_ENDE` VARCHAR(1000) NULL AFTER `REDE_LOGBLOK`, ADD COLUMN `REDE_NUM` VARCHAR(20) NULL AFTER `REDE_ENDE`, ADD COLUMN `REDE_BAIRRO` VARCHAR(300) NULL AFTER `REDE_NUM`, ADD COLUMN `REDE_CEP` VARCHAR(15) NULL AFTER `REDE_BAIRRO`, ADD COLUMN `REDE_CIDADE` VARCHAR(350) NULL AFTER `REDE_CEP`, ADD COLUMN `REDE_ESTADO` VARCHAR(350) NULL AFTER `REDE_CIDADE`;

ALTER TABLE `TREDE_USUADMIN` ADD COLUMN `REDE_CI_IBGE` INT(11) NULL AFTER `REDE_ESTADO`;

ALTER TABLE `TREDE_USUADMIN` CHANGE `REDE_CI_IBGE` `REDE_CI_IBGE` VARCHAR(30) NULL;

ALTER TABLE `TREDE_SINDICATO_USUA_CANCELADOS` CHANGE `CSTATSIUS` `CSITUSIUS` VARCHAR(10) CHARSET utf8 COLLATE utf8_unicode_ci NULL COMMENT 'SITUAÇÃO';

ALTER TABLE `TREDE_PERMISSAO` DROP COLUMN `MENUS3`, DROP COLUMN `SITUACAO`, DROP COLUMN `MENUS4`, DROP COLUMN `MENUS5`, CHANGE `MENUS1` `SITUACAO` INT(11) NULL COMMENT 'SITUAÇÃO', CHANGE `MENUS2` `DESCR` TEXT CHARSET utf8 COLLATE utf8_general_ci NULL COMMENT 'DESCR';


CREATE TABLE `TREDE_DADOS_BANCARIOS` ( `CNOMEBANCO` VARCHAR(200) COMMENT 'NOME DO BANCO', `NAGENBANCO` VARCHAR(20) COMMENT 'NUMERO DA AGENCIA COM DIGITO', `CONTABANCO` VARCHAR(20) COMMENT 'CONTA DO BANCO COM DIGITO', `NCPCJBANCO` VARCHAR(30) COMMENT 'CNPJ OU CPF', `CNOMFBANCO` VARCHAR(500) COMMENT 'NOME DO FAVORECIDO' );

ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `CCOMPRPPLAN` VARCHAR(400) NULL COMMENT 'ENDEREÇO DO COMPROVANTE' AFTER `NIDCODIPLAN1`, ADD COLUMN `CNOMCOPPLAN` VARCHAR(200) NULL COMMENT 'NOME DO COMPROVANTE DA IMAGEM' AFTER `CCOMPRPPLAN`, ADD COLUMN `DCOMPRPPLAN` DATETIME NULL COMMENT 'DATA DO ENVIO DO COMPROVANTE' AFTER `CNOMCOPPLAN`;

ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `DVENCBOPLAN` DATE NULL AFTER `DCOMPRPPLAN`, ADD COLUMN `CIDSEQPPLAN` VARCHAR(100) NULL AFTER `DVENCBOPLAN`, ADD COLUMN `CSTABOLPLAN` CHAR(1) NULL AFTER `CIDSEQPPLAN`;

CREATE TABLE `TREDE_JUROS_BOL` ( `JUROS_VENC` VARCHAR(10) COMMENT 'VALRO DO JUROS DO VENCIMENTO', `JUROS_DIA` VARCHAR(10) COMMENT 'JUROS POR DIA' );

ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `CSTABOLPLAN` CHAR(1) NULL COMMENT 'STATUS DO BOLETO' AFTER `CIDSEQPPLAN`;

ALTER TABLE `TREDE_PLANOS` ADD COLUMN `CCARNPLANO` CHAR(1) NULL COMMENT 'SABER SE VAI SER CARNE OU NAO' AFTER `DINCLPLANO`;

ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `NNUMCARPLAN` VARCHAR(40) NULL COMMENT 'ID DO CARNE' AFTER `CSICARNPLAN`;

ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `LINKCARNE` TEXT NULL COMMENT 'LINK DO CARNE GERAL' AFTER `NEXTNUMPLAN`;

ALTER TABLE `TREDE_PLANO` ADD COLUMN `CPORCPLANO` INT(11) NULL COMMENT 'PORCENTAGEM' AFTER `CCARNPLANO`;

ALTER TABLE `TREDE_PAGACOMPRA` ADD COLUMN `NVALCASHCOMPRA` VARCHAR(20) NULL COMMENT 'VALOR TOTAL DO CASHBACK' AFTER `NVALORCPAG`;

CREATE TABLE `TREDE_VENDEDOR` ( `NNUMEVEND` INT(11) AUTO_INCREMENT, `CNOMEVEND` VARCHAR(200), `CEMAIVEND` VARCHAR(250), `CSENHVEND` VARCHAR(100), `CBLOKVEND` CHAR(1), KEY(`NNUMEVEND`) );

CREATE TABLE `TREDE_VENDEDOR_USUA` ( `NNUMEVENU` INT(11), `NNUMESIND` INT(11), `NNUMEUSUA` INT(11), `DINCLVENU` DATETIME, `IDPGSEGPLAN` VARCHAR(30), `IDVENDEPLAN` VARCHAR(50) );

ALTER TABLE `TREDE_VENDEDOR_USUA` ADD COLUMN `NNUMEVEND` INT(11) NULL AFTER `NNUMEVENU`;

ALTER TABLE `TREDE_VENDEDOR_USUA` CHANGE `NNUMEVENU` `NNUMEVENU` INT(11) NULL AUTO_INCREMENT, ADD KEY(`NNUMEVENU`);

CREATE TABLE `TREDE_AFILIADOS_VEND` ( `NNUMEAFIL` INT(11) AUTO_INCREMENT, `NNUMEUSUA` INT(11), `NNUMEVEND` INT(11), `DINCLAFIL` DATETIME, KEY(`NNUMEAFIL`) );

ALTER TABLE `TREDE_AFILIADOS_VEND` ADD COLUMN `NNUMEPLAN` INT(11) NULL AFTER `DINCLAFIL`;

ALTER TABLE `TREDE_PLANOS` ADD COLUMN `LIBERAVEND` CHAR(1) NULL COMMENT 'LIBERAR PARA O CADASTRO DO SINCATO OU NÃO' AFTER `CPORCPLANO`;

CREATE TABLE `TREDE_VENDEDOR_PORC` ( `NNUMEPVEN` INT(11) AUTO_INCREMENT, `NNUMEVEND` INT(11), `CTIPOPVEN` CHAR(1), `NPORCPVEN` VARCHAR(10), `DLASTPVEN` DATETIME, KEY(`NNUMEPVEN`) );

---------------------------
MYCASHBACK

ALTER TABLE `TREDE_PAGAGERACASH` CHANGE `NVAGECSPAG` `NVAGECSPAG` VARCHAR(20) CHARSET utf8 COLLATE utf8_general_ci NULL COMMENT 'valor do cashback gerado', ADD COLUMN `CASHCOPPAG` VARCHAR(20) NULL COMMENT 'VALORO DO USUARIO QUE COMPROU' AFTER `CTIPOOPPAG`;

ALTER TABLE `TREDE_PRODUTOS` ADD COLUMN `DAUTPPRODU` DATETIME NULL COMMENT 'DATA DA AUTORIZAÇÃO DO PRODUTO' AFTER `CIMAGPRODU`;

CREATE TABLE `TREDE_WHATS` ( `NNUMWHATS` INT AUTO_INCREMENT, `NCELWHATS` VARCHAR(30), `CMSGWHATS` TEXT, KEY(`NNUMWHATS`) );

ALTER TABLE `TREDE_WHATS` ADD COLUMN `SEQUENCIACRE` VARCHAR(20) NULL COMMENT 'NUMERO DO CREDENCIADO' AFTER `CMSGWHATS`;

ALTER TABLE `TREDE_CREDENCIADOS` ADD COLUMN `CB2CCOINCCRE` VARCHAR(300) NULL COMMENT 'NUMERO DA CARTEIRA B2CCOIN' AFTER `REDE_SEQUSUA`;

ALTER TABLE `TREDE_PAGACOMPRA` ADD COLUMN `CSITUPAGCOMPRA2` VARCHAR(10) NULL COMMENT 'SITUAÇÃO DO PAGMAENTO, P- PENDENTE, E S PAGO, C CANCELADO' AFTER `CTIPOPAGMTOCOMP`;


CREATE TABLE `TREDE_CARTEIRA_B2C` ( `NNUMECART` INT AUTO_INCREMENT, `CCARTCART` VARCHAR(200) COMMENT 'ID DA CARTEIRA', `CTIPOCART` VARCHAR(10) COMMENT 'TIPOD E PESOA ADMIN OU USUSARIO', KEY(`NNUMECART`) );




/*******************************************************/

mimo

CREATE TABLE `TREDE_EMPRESAS_LAYOUT` ( `SEQEMLAY` INT(11) AUTO_INCREMENT, `NOMEEMPRESA` VARCHAR(1000) COMMENT 'NOME DA EMPRESA', KEY(`SEQEMLAY`) );
ALTER TABLE `TREDE_CONFIG_BASICS` ADD COLUMN `TEXTO` TEXT NULL COMMENT 'TEXTO DO BANNER' AFTER `ATIVO`;
ALTER TABLE `TREDE_CONFIG_BASICS` ADD COLUMN `EMPRESA` VARCHAR(500) NULL COMMENT 'NOME DA EMPRESA' AFTER `TEXTO`;


ALTER TABLE `TREDE_PAGAPLANO` ADD COLUMN `CSICARNPLAN` CHAR(1) NULL COMMENT 'SE É CARNE OU NÃO' AFTER `CSTABOLPLAN`;

ALTER TABLE `TREDE_EMPRESAS_LAYOUT` ADD COLUMN `LINKEMPRESA` VARCHAR(500) NULL AFTER `NOMEEMPRESA`;

ALTER TABLE `TREDE_CONFIG_BASICS` ADD COLUMN `IDEMPLAYOUT` INT(11) NULL COMMENT 'ID DA EMPRESA LAYOUT' AFTER `EMPRESA`;

ALTER TABLE `TREDE_CREDENCIADOS` ADD COLUMN `FACEBOOK` TEXT NULL AFTER `CLASSIFICCRE`, ADD COLUMN `INSTAGRAM` TEXT NULL AFTER `FACEBOOK`, ADD COLUMN `TWITER` TEXT NULL AFTER `INSTAGRAM`, ADD COLUMN `SKYPE` TEXT NULL AFTER `TWITER`, ADD COLUMN `LINKEDIN` TEXT NULL AFTER `SKYPE`;

ALTER TABLE `TREDE_USUADMIN` ADD COLUMN `REDE_COMPLE` TEXT NULL AFTER `REDE_DATAVENC`, ADD COLUMN `FACEBOOK` TEXT NULL AFTER `REDE_COMPLE`, ADD COLUMN `INSTAGRAM` TEXT NULL AFTER `FACEBOOK`, ADD COLUMN `TWITER` TEXT NULL AFTER `INSTAGRAM`, ADD COLUMN `SKYPE` TEXT NULL AFTER `TWITER`, ADD COLUMN `LINKEDIN` TEXT NULL AFTER `SKYPE`;

ALTER TABLE `TREDE_EMPRESAS_LAYOUT` ADD COLUMN `REDE_SEQUSUA` INT(11) NULL COMMENT 'o numero do usuario para poder fazer configurações' AFTER `LINKEMPRESA`;


CREATE TABLE `TREDE_PROFISSAO` ( `NNUMEPROF` INT(11) AUTO_INCREMENT, `CNOMEPROF` VARCHAR(200) COMMENT 'NOME DA PROFISSAO', `CTAGSPROF` INT(11) COMMENT 'TAG DA PROFISSAO', `CSITUPROF` CHAR(1), KEY(`NNUMEPROF`) );

ALTER TABLE `TREDE_CREDENCIADOS` ADD COLUMN `CTIPOCREDCRE` CHAR(2) NULL COMMENT 'TIPO SE É MEDICO SE É FISIO, CLINICA ETC' AFTER `LINKEDIN`, ADD COLUMN `NCONSELHOCRE` VARCHAR(20) NULL COMMENT 'NUMERO DO CONSELHO' AFTER `CTIPOCREDCRE`, ADD COLUMN `ESTACONSECRE` VARCHAR(5) NULL AFTER `NCONSELHOCRE`;

ALTER TABLE `TREDE_PROFISSAO` ADD COLUMN `NCATEPROF` INT(11) NULL COMMENT 'categoria que pertençe' AFTER `CSITUPROF`;

CREATE TABLE `TREDE_DOCS_CRED` ( `NNUMEDOC` INT(11) AUTO_INCREMENT, `CNOMEDOC` VARCHAR(200) COMMENT 'NOMECRIADO PELO SITEMA', `ARQNODOC` VARBINARY(200) COMMENT 'NOME DO ARQUIVO', `NNUMECRE` INT(11), KEY(`NNUMEDOC`) );

CREATE TABLE `TREDE_MSG_CONTATO` ( `NNUMECONT` INT(11), `CNOMECONT` VARCHAR(400), `CASSUCONT` VARCHAR(1000), `CEMAICONT` VARCHAR(1000), `XTEXTCONT` TEXT );
ALTER TABLE `TREDE_MSG_CONTATO` ADD COLUMN `DENVICONT` DATETIME NULL AFTER `XTEXTCONT`, ADD COLUMN `DRESPCONT` DATETIME NULL AFTER `DENVICONT`, ADD COLUMN `CSTATCONT` VARCHAR(2) NULL AFTER `DRESPCONT`;
ALTER TABLE `TREDE_MSG_CONTATO` CHANGE `NNUMECONT` `NNUMECONT` INT(11) NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (`NNUMECONT`);

CREATE TABLE `TREDE_CALENDARIO_CRED` ( `NNUMECALE` INT(11) NOT NULL AUTO_INCREMENT, `CNOMECALE` VARCHAR(500) COMMENT 'NOME DO EVENTO', `DINI_CALE` DATETIME COMMENT 'DATA INICIO', `DFIM_CALE` DATETIME COMMENT 'DATA FINAL', `SEQUENCIACRE` INT(11) COMMENT 'SEQ DA REDE', `REDE_SEQUSUA` INT(11) COMMENT 'SEQ DA USUARIO', `CSTATCALE` CHAR(2) COMMENT 'STATUS DO EVENTO', `CSITUCALE` CHAR(2) COMMENT 'SITUAÇÃO DO EVENTO', `CCOR_CALE` VARCHAR(10) COMMENT 'COR DO EVENTO', PRIMARY KEY (`NNUMECALE`) );

ALTER TABLE `TREDE_CALENDARIO_CRED` ADD COLUMN `CTIPOCALE` CHAR(2) NULL COMMENT 'TIPO DO EVENTO CONSULTA EXAME' AFTER `CCOR_CALE`;

ALTER TABLE `TREDE_CALENDARIO_CRED` ADD COLUMN `DDAGECALE` DATETIME NULL COMMENT 'DIA DO AGENDAMENTO' AFTER `CTIPOCALE`, ADD COLUMN `DPAGACALE` DATETIME NULL COMMENT 'DIA HORA DO PAGAMENTO' AFTER `DDAGECALE`;

ALTER TABLE `TREDE_CALENDARIO_CRED` ADD COLUMN `NVALOCALE` VARCHAR(20) NULL COMMENT 'VALOR DO EVENTO' AFTER `DPAGACALE`;

CREATE TABLE `TREDE_TIPO_EVENTO` ( `NNUMEEVENT` INT(11) NOT NULL AUTO_INCREMENT, `CNOMEEVENT` VARCHAR(500), `CSTATEVENT` CHAR(2), `DCRIAEVENT` DATETIME, `SEQUENCIACRE` INT, PRIMARY KEY (`NNUMEEVENT`) );

CREATE TABLE `TREDE_PAGACALENDARIO` ( `NNUMEPCAL` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'SEQ', `NNUMEUSUA` INT(11) COMMENT 'NUMERO DO USUARIO', `SEQUENCIACRE` INT(11) COMMENT 'COD DO CREDENCIADO', `NNUMECALE` INT(11) COMMENT 'CHAVE DO CALENDARIOCRED', `DRESEPCAL` DATETIME COMMENT 'DATA DA RESERVA', `STAPGPCAL` INT(11) COMMENT 'STATUS DO PAGAMENTO', `CTIPPGCAL` INT(11) COMMENT 'TIPO DE PAGAMENTO', `PAGLOPCAL` CHAR(1) COMMENT 'SE PAGAMENTO É LOCAL OU NAO', PRIMARY KEY (`NNUMEPCAL`) );

ALTER TABLE `TREDE_CALENDARIO_CRED` ADD COLUMN `CTIMECALE` VARCHAR(20) NULL COMMENT 'TIPO EM MINUTOS ENTRE UMA CONSULTA E OUTRA' AFTER `NVALOCALE`;

ALTER TABLE `TREDE_PAGACALENDARIO` ADD COLUMN `DCRIAPCAL` DATETIME NULL COMMENT 'DATA HORA  DO CRIAMENTO' AFTER `PAGLOPCAL`;

ALTER TABLE `TREDE_PAGACALENDARIO` CHANGE `CTIPPGCAL` `CTIPPGCAL` VARCHAR(11) NULL COMMENT 'TIPO DE PAGAMENTO', CHANGE `PAGLOPCAL` `PAGLOPCAL` VARCHAR(3) CHARSET utf8 COLLATE utf8_unicode_ci NULL COMMENT 'SE PAGAMENTO É LOCAL OU NAO';

ALTER TABLE `TREDE_PAGACALENDARIO` ADD COLUMN `PAGOLOCAL` CHAR(1) NULL COMMENT 'SE FOI AUTORIZADO PELA REDE' AFTER `DCRIAPCAL`;

ALTER TABLE `TREDE_CALENDARIO_CRED` ADD COLUMN `STIMECALE` INT(11) NULL COMMENT 'TEMPO QUE FOI RESGISTRADO EM STRING TO TIME' AFTER `CTIMECALE`;

ALTER TABLE `TREDE_TIPO_EVENTO` ADD COLUMN `CTEMPEVENT` CHAR(10) NULL COMMENT 'TEMPOD E DURAÇÃO DO EVENTO' AFTER `SEQUENCIACRE`;

ALTER TABLE `TREDE_CREDENCIADOS` ADD COLUMN `CTIPOCRED` INT(11) NULL COMMENT 'TIPO DE CREDENCIADOS : 1 - serviços, 2- produtos, 3 - os dois' AFTER `ESTACONSECRE`;